### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by Ryan-dp** [TheLovinator1/discord-twitter-webhooks#1]
2019-10-23 13:19:35,288 ERROR        Error: 406
2019-10-23 13:19:41,477 ERROR        Error: 406
2019-10-23 13:19:52,752 ERROR        Error: 406
2019-10-23 13:20:14,164 ERROR        Error: 406
2019-10-23 13:20:55,472 ERROR        Error: 406
2019-10-23 13:22:20,760 ERROR        Error: 406
2019-10-23 13:25:02,640 ERROR        Error: 406

**Comment by TheLovinator1** [comment]
Have you modified the code?

And your config.ini should look something like this:

```
[discord]
webhook_url = https://discordapp.com/api/webhooks/87629431744371866618/XWx4oZctMiliGhqA6xKSXWx4oZctMiliGhqA6xKSXWx4oZctMiliGhqA6xKS-ukRePERn-kekrWb0fYMbgQBEg9Tgn
webhook_error_url = https://discordapp.com/api/webhooks/87629431744371866618/XWx4oZctMiliGhqA6xKSXWx4oZctMiliGhqA6xKSXWx4oZctMiliGhqA6xKS-ukRePERn-kekrWb0fYMbgQBEg9Tgn

[twitter]
consumer_key = uXCoFuGelkHWWVkgtYDg
consumer_secret = akSWodGsnGSLnyioyeSyakSWodGsnGSLnyioyeSy
access_token = 7590329167-MYlEJVmbWMBGsEKgshRWMYlEJVmbWMBGsEKgshRW
access_token_secret = APspzJmSoDfWAqtHTPeNAPspzJmSoDfWAqtHTPeN
users_to_follow = 1114707756, 36803580
```

**Comment by Ryan-dp** [comment]
yes I got it but can you make more faster ?

**Comment by Ryan-dp** [comment]
![c1](https://user-images.githubusercontent.com/56335280/67447133-26889a00-f5d0-11e9-8547-35e6122982bb.png)
how Can I fix to the actual link?

**Comment by TheLovinator1** [comment]
> ![c1](https://user-images.githubusercontent.com/56335280/67447133-26889a00-f5d0-11e9-8547-35e6122982bb.png)
> how Can I fix to the actual link?

I fixed this in the latest update. Sorry for not fixing it earlier
