### ISSUE TITLE
Twitter Restricts Filtered Stream API to Enterprise

### ISSUE THREAD

**Issue by EthanC** [TheLovinator1/discord-twitter-webhooks#110]
Although it has slowly rolled out, as my access was only cut off in the last 24 hours, Twitter now restricts access to the Filtered Stream API that this project relies on to the [Enterprise tier](https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api). Today, my Docker instance of this project could not authenticate...

```py
Traceback (most recent call last):
  File "/discord_twitter_webhooks/main.py", line 244, in <module>
    start()
  File "/discord_twitter_webhooks/main.py", line 200, in start
    delete_old_rules(stream=stream)
  File "/discord_twitter_webhooks/rules.py", line 23, in delete_old_rules
    old_rules = stream.get_rules()
                ^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/tweepy/streaming.py", line 480, in get_rules
    return self._make_request(
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/tweepy/client.py", line 129, in _make_request
    response = self.request(method, route, params=request_params,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/pysetup/.venv/lib/python3.11/site-packages/tweepy/client.py", line 100, in request
    raise Forbidden(response)
tweepy.errors.Forbidden: 403 Forbidden
When authenticating requests to the Twitter API v2 endpoints, you must use keys and tokens from a Twitter developer App that is attached to a Project. You can create a project via the developer portal.
```

I see there is a [rewrite branch](https://github.com/TheLovinator1/discord-twitter-webhooks/tree/rewrite) of this project that appears to remove the API dependency and instead uses RSS feeds. This appears to be the best solution moving forward. Is this still in active development? Could a Docker image be provided for us to use?

Regardless, thanks for your work, @TheLovinator1

**Comment by TheLovinator1** [comment]
Hi, the rewrite is 95% done, so I still need a little more time before it is complete. I will post it here when it is done. Sorry for not being ready when the API died.

**Comment by thatjk** [comment]
Also hit the issue of my docker instance could not authenticate earlier today as well, any eta of the update, not to rush just more curiosity. Thanks for your hard work

**Comment by dziban303** [comment]
My API access has been killed off as of today. Eagerly awaiting the RSS rewrite.

**Comment by EthanC** [comment]
The rewrite appears to have relied on [nitter](https://nitter.net/), per the following line:

https://github.com/TheLovinator1/discord-twitter-webhooks/blob/25a0e9ff4f2c50a2acd097eb371ea92e3b706c24/discord_twitter_webhooks/add_new_feed.py#L184

Twitter [no longer provides data to unauthenticated users](https://www.engadget.com/elon-musk-claims-twitters-new-login-requirement-is-a-temporary-response-to-data-scrapers-160041528.html), effectively killing nitter. Research is [ongoing](https://github.com/zedeus/nitter/issues/919#issuecomment-1619298877) for ways around this new limitation, but @TheLovinator1's project can't progress without the upstream issue being resolved first.

**Comment by TheLovinator1** [comment]
Hi, sorry for disappearing.

As Ethan said, I am using RSS feeds from Nitter for getting tweets but that broke
when Elon shut down the API that Nitter uses. 

Elon says it is temporary, but I have no idea how long that will be. Or if we can even trust him.

If this doesn't get fixed soon, I guess I will have to find another way to get tweets. (Or just give up lol)

**Comment by Vilemouse** [comment]
Just chiming in here. the restriction has been lifted so nitter should work again

**Comment by TheLovinator1** [comment]
Hi, I merged the `rewrite` branch with `master`. 

The [README](https://github.com/TheLovinator1/discord-twitter-webhooks) has instructions how to run the bot. I have to sleep now, but feel free to reply/create a new issue for everything that is missing or broken.

Sorry again for taking so long to fix this

**Comment by dziban303** [comment]
Awesome! I couldn't get it up and running on the Pi4 I'd been using previously; it wanted ffmpeg, so I installed it and added the envar pointing to it. Then it threw a sql error, to wit: `reader.exceptions.StorageError: error while opening database: sqlite3.OperationalError: unable to open database file` *shrug*

I just wanted to get it running, so I tried it in docker on a windows machine: it worked like a charm. I'll look at setting up a nitter instance tomorrow (or in the next few days, anyway, you know how it is) to support my own use case. 

Is text filtering planned? 

Thank you so much for getting this back up and running. We've been missing it!

Cheers

**Comment by EthanC** [comment]
Successfully running the rewrite in Docker on Ubuntu; thanks for your hard work!

Because this project now relies on Nitter RSS feeds, there seems to be a delay between a Tweet being posted and it being posted to the Discord Webhook - which wasn't the case before. I wondering if the default Nitter instance could set [`rssMinutes`](https://github.com/zedeus/nitter/blob/f881226b223f1650f7f1621991baa38513ddb61f/nitter.example.conf#L12C16-L12C16) to `1` (or even `0`) to alleviate this issue?
