### ISSUE TITLE
Add Toggle for Tweets Containing Media

### ISSUE THREAD

**Issue by EthanC** [TheLovinator1/discord-twitter-webhooks#118]
In the previous version, we could filter to only Tweets with media attached using the `has:media` flag in the search query.

It would be great to see this functionality return as a togglable feed option!

**Comment by TheLovinator1** [comment]
I added a toggle for this, but I am checking for both gifs and images. Should I add two separate toggles instead?

**Comment by EthanC** [comment]
Personally, I would expect "media" to include images, GIFs, and videos, but I could see someone else needing more granularity.
