### ISSUE TITLE
Add Keyword Filter for Tweets

### ISSUE THREAD

**Issue by EthanC** [TheLovinator1/discord-twitter-webhooks#119]
In the previous version, we could filter for Tweets containing specific keywords in the search query. For example, the following query would only post Tweets to the webhook if the words "sale", "discount" or "deal" were in the Tweet body.

- `(sale OR discount OR deal) from:Steam`

This functionality could be re-implemented in the rewrite by adding a text field containing the required keywords for a feed.

**Comment by EthanC** [comment]
On the opposite end of the `OR` search operator, there's `AND`. This functionality would be appreciated as well. For example, the following query would only post Tweets to the webhook if the words "rust" and "deal" were in the Tweet body.

- `(rust AND deal) from:Steam`

**Comment by TheLovinator1** [comment]
Hi, sorry for not being faster with this.

I added two ways to whitelist/blacklist tweets. The first one is just checking if the string is in the tweet and the other one is using regex. I have to add a way to see what tweets gets blocked/allowed but this should be a start.

Right now I am just doing:

```
If not whitelisted:
    continue
If blacklisted:
    continue
```

Should it be like this instead?


```
If not whitelisted:
    continue
If blacklisted:
    If whitelisted:
        send_even_if_blacklisted()
    continue
```

**Comment by dziban303** [comment]
For my purposes, the current implementation is best. I currently only have one feed configured with both white and blacklists: I want the tweets with whitelisted strings posted, unless the one blacklist word appears. If I understand correctly, the second option you mention would break that functionality and post it anyway. I can see situations where that would be useful, but I'd say leave it as-is unless someone requests it :)

We really appreciate your work on this!

**Comment by EthanC** [comment]
The current implementation is probably best as it's simpler for the user and less work for you. Much appreciated!
