### ISSUE TITLE
Embed Link Directly to Twitter, not Nitter

### ISSUE THREAD

**Issue by EthanC** [TheLovinator1/discord-twitter-webhooks#123]
Opening an Issue for tracking this request as I recall seeing a commit commenting it as a TODO.

Either per-feed or globally, it would be great to have a toggle to use native Twitter links in Embeds, rather than Nitter links.

**Comment by TheLovinator1** [comment]
The default is now:
Twitter instead of Nitter
YouTube instead of Piped/Invidious
Reddit instead of Teddit/Libreddit
