### ISSUE TITLE
Image Gallery Embed Detached from Tweet Embed

### ISSUE THREAD

**Issue by EthanC** [TheLovinator1/discord-twitter-webhooks#135]
Seeing this cosmetic issue on the latest version. I believe the URL (and title?) of each embed needs to match for the image gallery to merge, allowing for one seamless embed - as you see when pasting the Tweet link into Discord as a user.

* Tweet: https://twitter.com/BKTOOR_/status/1683976829189730305

![image](https://github.com/TheLovinator1/discord-twitter-webhooks/assets/16727756/ecbcba30-340b-46e1-ba03-5528c2104608)

**Comment by TheLovinator1** [comment]
Oops, the embed at the top used Nitter and the other 3 used Twitter

Should be fixed now

Thanks for telling me
