### ISSUE TITLE
Keywords

### ISSUE THREAD

**Issue by logandiros** [TheLovinator1/discord-twitter-webhooks#28]
Any chance keywords would work?

**Comment by TheLovinator1** [comment]
No, but other bots has support for that:
[NNTin/discord-twitter-bot](https://github.com/NNTin/discord-twitter-bot) 
[MEE6](https://mee6.xyz/tutorials/how-to-automatically-post-tweets-to-discord-using-mee6)
[TweetShift](https://tweetshift.com/) (This looks really professional but I have never used it so ¯\\_(ツ)_/¯)
