### ISSUE TITLE
Tweets are not posted

### ISSUE THREAD

**Issue by Aida-Enna** [TheLovinator1/discord-twitter-webhooks#72]
I've tried with a few different accounts/webhooks and nothing gets posted.

```
user@server# docker run --env-file=/home/TwitterBot/.env 91657908f2fb
08:17:32 INFO Rule 0: RULE="from:GranblueRdmAcct" will get send to https://discord.com/api/webhooks/1073179489057648691/bleh
08:17:35 INFO Rule 1638454858926764038 added to Twitter.com
08:17:35 INFO Stream connected
```

if I turn on debug mode I can see it create the rule and Twitter accept it, but when I tweet, nothing happens.

Here's the relevant parts from the config:
```
WEBHOOK_URL=https://discord.com/api/webhooks/1088027533385138176/TEqzA5JzwhfxNu4dIpp17iHPB-CO9LZQrb_Ir6do_SL81guldkf60PFo6u4NVYWZ-zl9
RULE="from:GranblueRdmAcct"
ERROR_WEBHOOK=https://discord.com/api/webhooks/1088027533385138176/TEqzA5JzwhfxNu4dIpp17iHPB-CO9LZQrb_Ir6do_SL81guldkf60PFo6u4NVYWZ-zl9
SEND_ERRORS=True
LOG_LEVEL=DEBUG
TWITTER_IMAGE_COLLAGE_API=https://twitter.lovinator.space/add
```
everything else is default. I have elevated access from having a developer account from years ago.

(I created a brand new empty server for that webhook)

**Comment by TheLovinator1** [comment]
Can you try to change the rule to `RULE=from:GranblueRdmAcct` without the quotes?

**Comment by TheLovinator1** [comment]
I added code that removes the quotes before and after the rule, it should fix this issue if the previous comment was the issue.

**Comment by TheLovinator1** [comment]
Please reopen if the problem still persists, thanks.
