### ISSUE TITLE
Discord Canary Webhook URLs Invalid for ERROR_WEBHOOK

### ISSUE THREAD

**Issue by EthanC** [TheLovinator1/discord-twitter-webhooks#83]
The `ERROR_WEBHOOK` environment variable seems to invalidate webhook URLs copied from the Discord Canary client. This could be fixed by removing `canary.` from the URL, but seeing as a warning is not thrown for canary URLs on `WEBHOOK_URL`, this seems to be a bug.

I'm not sure if this prevents errors from being sent or not as I've never received an error on this webhook 👀 

```
WARNING Your ERROR_WEBHOOK does not start with https://discord.com/api/webhooks/, is this correct? It is currently set to 'https://canary.discord.com/api/webhooks/XXXXXXXXXX/XXXXXXXXXX'
```

**Comment by TheLovinator1** [comment]
Hi,

It just warns, so I will wait till tomorrow to make it stop complaining when using a canary or PTB webhook. I guess there is no difference between the subdomains so not worth removing the canary part?

**Comment by dziban303** [comment]
There's also `ptb.` subdomain for people using the PTB client, which is—well, I dunno, if Canary is a βeta client then PTB would be release candidate? There is no functional difference. I just habitually drop the subdomain from webhook URLs out of an abundance of caution.

**Comment by TheLovinator1** [comment]
I am now checking that webhook works instead of just checking if it starts with https://discord.com/api/webhooks/ :-)
