### ISSUE TITLE
Bug: Can't use multiple webhooks in a single rule

### ISSUE THREAD

**Issue by dziban303** [TheLovinator1/discord-twitter-webhooks#86]
With the latest image, I would get this error when trying to turn up the stack:

```
dtw  | 2023-04-01 at 18:46:14 ERROR 404: Not Found
dtw  | 404 Not Found - I can't connect to https://discord.com/api/webhooks/(blah blah),https://discord.com/api/webhooks/(another blah blah), please check if it is a valid webhook.
```

This rule, sending the same notification to two different webhooks, had worked in the previous version.

To check if the webhook URL was valid, I created a separate webhook and rule combo using the second webhook URL (with a slightly different rule, as it can't run the same exact rule in a different webhook). This time it works, so it seems it may not be parsing the comma correctly in `WEBHOOK_URLx=https://url1,https://url2,...`

**Comment by TheLovinator1** [comment]
Oops, fixed in https://github.com/TheLovinator1/discord-twitter-webhooks/commit/e64db2b64e62603629cfc06f40e7e896634c83be, need ~5 min to build Docker images

**Comment by TheLovinator1** [comment]
Should be working now
