### ISSUE TITLE
Revenge of the t.cos and UTMs

### ISSUE THREAD

**Issue by dziban303** [TheLovinator1/discord-twitter-webhooks#87]
The t.co shortened URLs are back—sometimes:

![image](https://user-images.githubusercontent.com/7931765/229371149-c1f82d35-0f51-4e2f-ac0a-33f301d150dd.png)

In the first tweet ([original](https://twitter.com/volcanodiscover/status/1642532366362066949)) the t.co link appears, followed by the unobfuscated link. As you can see in the original tweet, only one link was in the tweet. Curiously, the unobfuscated link includes the `?t=...` parameter which does not appear to be included in the original link or used by the volcano discovery website. I'm not sure where that came from.

In the second tweet ([original](https://twitter.com/raspishakEQ/status/1642590713119494150)) both of the links supplied in the tweet failed to convert from the t.co link to the original URL.

`CONVERT_TCO_LINKS` envar was not explicitly defined in the .env.

Lastly, here's the third tweet in the series:

![image](https://user-images.githubusercontent.com/7931765/229371588-1c211a4f-bccc-41d5-8aa0-25ec7f97ede0.png)

In this tweet ([original](https://twitter.com/USGSted/status/1642593251843801088)), there's no t.co link at all, but all the UTM parameters are present. In this case, the `REMOVE_UTM=True` envar was explicitly defined in the .env.

Running the latest image.

**Comment by EthanC** [comment]
I'm seeing this as well while running the latest Docker image. I've not defined `CONVERT_TCO_LINKS` in my environment variables as it should default to `true` per [`.env.example`](https://github.com/TheLovinator1/discord-twitter-webhooks/blob/master/.env.example). Here is an example Tweet link and a screenshot of the embed...

https://twitter.com/COD_Esports/status/1644067889174007828

![image](https://user-images.githubusercontent.com/16727756/230490232-71264d8b-4491-4d0d-9b9e-17265aa69306.png)
