### ISSUE TITLE
Retweets Are Truncated at 140 Characters

### ISSUE THREAD

**Issue by EthanC** [TheLovinator1/discord-twitter-webhooks#92]
It appears the text of Retweeted Tweets will be truncated to 140 characters. This does not occur for regular Tweets, only Retweets.

**Example**

* Retweet: https://twitter.com/InfinityWard/status/1644093247948484609
* Original Tweet: https://twitter.com/COD_Esports/status/1644067889174007828

![image](https://user-images.githubusercontent.com/16727756/230540933-675f70a0-b718-40d3-8ba8-3fa9ba931169.png)

**Comment by TheLovinator1** [comment]
This should work now
