### ISSUE TITLE
Tweets Are Truncated at 280 Characters

### ISSUE THREAD

**Issue by EthanC** [TheLovinator1/discord-twitter-webhooks#96]
The text of all Tweets appears to be limited to 280 characters. However, Twitter Blue allows for [up to 10,000 characters](https://twitter.com/elonmusk/status/1637956239891070976?s=20) while Discord Embed descriptions allow for [up to 4,096 characters](https://discord.com/developers/docs/resources/channel#embed-object-embed-limits). Ideally, this project should truncate at the embed description limit.

**Example**

* https://twitter.com/charlieINTEL/status/1646556919752949761

![image](https://user-images.githubusercontent.com/16727756/231842815-354a5359-a199-48c7-8950-02ee35fb625a.png)

**Comment by TheLovinator1** [comment]
This should work now
